---
name: 'newsletter'
---

SiteConfig:
  extensions:
    - NewsletterSiteConfigExtension

Page_Controller:
  extensions:
    - NewsletterPageControllerExtension

SubscriptionAdmin:
  awesome_icon: envelope